// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.last_seen_buildid", "20200403170909");
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.startupExperimentPrefs.browser.search.param.google_channel_row", "trow2");
user_pref("app.normandy.startupExperimentPrefs.browser.search.param.google_channel_us", "tus2");
user_pref("app.normandy.startupExperimentPrefs.privacy.annotate_channels.strict_list.enabled", true);
user_pref("app.normandy.startupExperimentPrefs.urlclassifier.trackingAnnotationTable.testEntries", "etp-experiment-1.dummytracker.org");
user_pref("app.normandy.startupRolloutPrefs.app.normandy.onsync_skew_sec", 3300);
user_pref("app.normandy.user_id", "ff35c517-843e-49df-a59d-9673eaf68b9f");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 1586615421);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1586615181);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1586615048);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1586615301);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1586615211);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir2.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 11343);
user_pref("browser.cache.disk.capacity", 890880);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1586615043);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 92);
user_pref("browser.newtabpage.activity-stream.impressionId", "{fbfd63db-672b-44e9-84d8-3ac9ae684431}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1586615180376");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1586616971376");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1586615046862");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1586618646862");
user_pref("browser.search.cohort", "nov17-1");
user_pref("browser.search.region", "NL");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200403170909");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1586615838");
user_pref("browser.slowStartup.averageTime", 2448);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20200403170909");
user_pref("browser.startup.homepage_override.mstone", "75.0");
user_pref("browser.startup.lastColdStartupCheck", 1586615838);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.tipShownCount.searchTip_onboard", 4);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1586615044822");
user_pref("distribution.iniFile.exists.appversion", "75.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "5fd69feca7fc408fab6899577f9a43b8");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200403170909");
user_pref("extensions.lastAppVersion", "75.0");
user_pref("extensions.lastPlatformVersion", "75.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"d4c02669-609c-4986-9e6f-6627f84901d8\",\"formautofill@mozilla.org\":\"108f5a83-f529-4e94-92c8-647230a5fe3e\",\"screenshots@mozilla.org\":\"1d2b517a-0ca9-4e8a-a260-ca511f0d6534\",\"webcompat-reporter@mozilla.org\":\"b90130c9-0499-4836-a3f0-f7522116e3e9\",\"webcompat@mozilla.org\":\"3f905d9f-7b38-4886-9a09-a88431492dff\",\"default-theme@mozilla.org\":\"01846b68-c68c-47e1-b378-896a100d3f6c\",\"google@search.mozilla.org\":\"e49bfdb6-3026-42ca-88a9-ed6163d626ac\",\"amazondotcom@search.mozilla.org\":\"c90159c4-998e-4fe4-bf08-e03ca28fd131\",\"bing@search.mozilla.org\":\"b2c0006f-f5d6-4884-9517-70eb6050eb06\",\"ddg@search.mozilla.org\":\"9fd322dc-41d5-4e8a-96e6-57278b8df50d\",\"ebay@search.mozilla.org\":\"bfaa5aaf-374b-4bdc-b31a-97d9c9265d20\",\"twitter@search.mozilla.org\":\"8881dc2b-9448-4420-899c-91938884580d\",\"wikipedia@search.mozilla.org\":\"735fe3a7-9a36-4891-99b1-a0c777aff49e\"}");
user_pref("gfx.crash-guard.status.wmfvpxvideo", 2);
user_pref("gfx.crash-guard.wmfvpxvideo.appVersion", "75.0");
user_pref("gfx.crash-guard.wmfvpxvideo.deviceID", "0x3e94");
user_pref("gfx.crash-guard.wmfvpxvideo.driverVersion", "26.20.100.7263");
user_pref("layers.mlgpu.sanity-test-failed", false);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.advanced-layers", true);
user_pref("sanity-test.device-id", "0x3e94");
user_pref("sanity-test.driver-version", "26.20.100.7263");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20200403170909");
user_pref("sanity-test.webrender.force-disabled", false);
user_pref("security.sandbox.content.tempDirSuffix", "{a9b592c5-8ebf-4fd1-9085-32ca731a50d7}");
user_pref("security.sandbox.plugin.tempDirSuffix", "{c02e0e02-d4c6-46ff-b7f2-56cbd4ed5360}");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1586615837);
user_pref("toolkit.telemetry.cachedClientID", "66497abb-3dc5-4c92-a075-c00cbbb67a10");
user_pref("toolkit.telemetry.previousBuildID", "20200403170909");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
